title: TopoCluster
# logo: /assets/img/logo.png
description: TopoCluster is a localized data structure for simplicial meshes, and it provides efficient computation of the connectivity of the mesh elements with a low memory footprint. 
show_downloads: true
theme: jekyll-theme-minimal
